#!/usr/bin/env python


import sys
import click
import subprocess

def runcmd(*args):
	print(*args)
	return 0

@click.command()
@click.option('--dryrun','-n',is_flag=True,default=False) #,help='the name of the release')
@click.argument('version',default="") #,help='the name of the release')
def main(dryrun,version):
	if dryrun:
		run = runcmd
	else:
		run = subprocess.call

	with open("VERSION","rt") as fi:
		oldv = fi.read().strip()
	if version == "":
		click.echo("current version: "+oldv)
		sys.exit(1)
	if oldv == version:
		click.echo("version number not changed")
		sys.exit(2)

	# XXX check that the new version number is kosher

	retcode = run(["git","tag", "-a",version, "-m", version])
	if retcode != 0:
		sys.exit(retcode)
	with open("VERSION","wt") as fo:
		fo.write(version)
	retcode = run(["git","push","origin","--tags"])
	if retcode != 0:
		sys.exit(retcode)

	retcode = run([sys.executable,"setup.py","sdist","upload"])
	if retcode != 0:
		sys.exit(retcode)

if __name__=='__main__':
	main()
